{% set name = "permamodel" %}
{% set version = "0.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f6f430135b2d59a07764a04254e91cb20fccdea79f208a2b21b324d043930a1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy
    - scipy
    - netcdf4
    - xarray
    - affine
    - python-dateutil
    - pyyaml
    - toml

test:
  imports:
    - permamodel
    - permamodel.components

about:
  home: https://permamodel.github.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of numerical permafrost models.
  description: |
    Permamodel is a collection of numerical permafrost models with a range of
    capability and complexity. Permamodel includes multiple sets of sample
    inputs representing a variety of conditions and locations. The Permamodel
    project is intended to facilitate the broader use of permafrost models. We
    hope that the simple Python interfaces and open source licensing can make
    permafrost models accessible to a broad audience well beyond the permafrost
    research community, such as educators, students, and policy makers.
  dev_url: https://github.com/permamodel/permamodel

extra:
  recipe-maintainers:
    - mcflugen
    - mdpiper
