travis:
  secure:
    BINSTAR_TOKEN: JZRCwH6eZJqeCrtTtFp0z0DbLF5H+cuP00t6tIytw7+biC13LG273Q3jXPRwx085GmvAwufaJfkSfhmfbqV8M1E+by3le6gBYTUzN19+OmgmdTwldk9nrUPkDXODXReio9E2//YPhKZ6W16tSuQ2J2tu9IXHVPWp6et0GhYvbqSIvIC3ibxiNdzLksO7q3bIsyxIaOduQZGxc04jvkthKZyVNmdGzk0Ao28aPQ5PMWUfPMF2oDJrzFd5AEiI0ksWT34d9Ag3sQ7prI3BgP8rGC4wvnyiznZ8MfljhMsHlvoIA0B+w/22CRXC+TUQ4PmLALQBxBZkPZGnZLnBVKIkXQbRCwz3PIv9yGXNBZ2IvVBRd0kgZKdqZchBVgHuU2V0m+VyypQFgwON+nVaqWnNts3MSsS+3GPdPL6FUEzdFxEie9mg18lySFJV1hHItd2jHbNdlkke4zfHGRKhQMPLVW3q2WunWCeBKxt95U1HJk+i8rKTE66PY+LInk0TSGCW4mP9JwLUio1MbFAFKK68KQjN4qrln/e+/reeD11CFBFaZMY34432ozdHdnLH158hEsmWABsnLYhAB4YNG4VLF/D3ywxeeTtiZf5Cr1xRH0QV+8adQ2oCLlS/xqge/GQbtcGsndhpJgsredsan+eYjDHd0ibzpGv7uB7qPp5RDi8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
